name: Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Se ejecuta diariamente a medianoche
  workflow_dispatch: # Permite ejecuci칩n manual desde la pesta침a Actions

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Generar la animaci칩n del snake
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: ELISEOKING # Tu nombre de usuario
          outputs: dist/snake.svg

      - name: Publicar la animaci칩n
        run: |
          mkdir -p assets
          mv dist/snake.svg assets/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/snake.svg
          git commit -m "Actualiza snake.svg"
          git push
